### ISSUE TITLE
error occur in index.js Line 27

### ISSUE THREAD

**Issue by renkeEdogawa** [Voxelstice/rxdata-map-to-json#1]
https://github.com/Voxelstice/rxdata-map-to-json/blame/75c97bf2e17f826a1b9e70b1a0322551548ee462/index.js#L27

hi,Is there a bug in this line of code?about "rxdata.className".
when I run this script, error occured as follows,and nothing appears in the folder "out_putFiles"

renke@win10:~/work/rxdata-map-to-json-main$ node .
/home/renke/work/rxdata-map-to-json-main/index.js:27
        if (Symbol.keyFor(rxdata.className) == "RPG::Map") {
                   ^

TypeError: undefined is not a symbol
    at Function.keyFor (<anonymous>)
    at doProcess (/home/renke/work/rxdata-map-to-json-main/index.js:27:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.2.0
![referencePicture](https://github.com/Voxelstice/rxdata-map-to-json/assets/68655287/880a4eca-6f72-4fb2-9176-5509c2120a1e)

**Comment by Voxelstice** [comment]
This little thing i made is badly written and does not work too well, i honestly have no idea how the code works at this point of time

**Comment by renkeEdogawa** [comment]
That's ok.I find anothor tool works well. 
https://github.com/GamingLiamStudios/rxdataToJSON
